#!/usr/bin/env python3

from pymongo import MongoClient


def list_databases():
    client = MongoClient('localhost', 27017)

    databases = client.list_database_names()
    print("Databases:")
    for db_name in databases:
        db = client[db_name]
        stats = db.command("dbstats")
        storage_size_gb = stats['storageSize'] / (1024 * 1024 * 1024)
        print(f"{db_name:<10} {storage_size_gb:.3f}GB")

if __name__ == "__main__":
    list_databases()
